<?php

namespace Librinfo\VarietiesBundle\Entity\Repository\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:50:33.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Entity\Repository\PlantCategoryRepository;


class PlantCategoryRepositoryTest extends TestCase
{
    /**
     * @var PlantCategoryRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new PlantCategoryRepository;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
