<?php

namespace Librinfo\VarietiesBundle\Form\Type\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:55:36.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionFilterType;


class VarietyDescriptionFilterTypeTest extends TestCase
{
    /**
     * @var VarietyDescriptionFilterType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionFilterType;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionFilterType::buildForm
     * @todo   Implement testBuildForm().
     */
    public function testBuildForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionFilterType::configureOptions
     * @todo   Implement testConfigureOptions().
     */
    public function testConfigureOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionFilterType::getBlockPrefix
     * @todo   Implement testGetBlockPrefix().
     */
    public function testGetBlockPrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
