<?php

namespace Librinfo\VarietiesBundle\Form\Type\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:53:58.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionType;


class VarietyDescriptionTypeTest extends TestCase
{
    /**
     * @var VarietyDescriptionType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionType;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionType::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionType::getBlockPrefix
     * @todo   Implement testGetBlockPrefix().
     */
    public function testGetBlockPrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\Type\VarietyDescriptionType::configureOptions
     * @todo   Implement testConfigureOptions().
     */
    public function testConfigureOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
