<?php

namespace Librinfo\VarietiesBundle\CodeGenerator\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:42:10.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\CodeGenerator\VarietyCodeGenerator;


class VarietyCodeGeneratorTest extends TestCase
{
    /**
     * @var VarietyCodeGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyCodeGenerator;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\CodeGenerator\VarietyCodeGenerator::setEntityManager
     * @todo   Implement testSetEntityManager().
     */
    public function testSetEntityManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\CodeGenerator\VarietyCodeGenerator::generate
     * @todo   Implement testGenerate().
     */
    public function testGenerate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\CodeGenerator\VarietyCodeGenerator::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\CodeGenerator\VarietyCodeGenerator::getHelp
     * @todo   Implement testGetHelp().
     */
    public function testGetHelp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
