<?php

namespace Librinfo\VarietiesBundle\Entity\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:48:10.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner;


class VarietyDescriptionInnerTest extends TestCase
{
    /**
     * @var VarietyDescriptionInner
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionInner;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner::getFieldset
     * @todo   Implement testGetFieldset().
     */
    public function testGetFieldset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
