<?php

/*
 * This file is part of the Blast Project package.
 *
 * Copyright (C) 2015-2017 Libre Informatique
 *
 * This file is licenced under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Librinfo\VarietiesBundle\Entity\Test\Unit;

/*
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-29 at 18:00:51.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional;

class VarietyDescriptionProfessionalTest extends TestCase
{
    /**
     * @var VarietyDescriptionProfessional
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VarietyDescriptionProfessional();
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionProfessional;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional::getFieldset
     *
     * @todo   Implement testGetFieldset().
     */
    public function testGetFieldset()
    {
        $test = $this->object->getFieldset();
        $this->assertEquals($test, 'professional');
    }
}
