<?php

namespace Librinfo\VarietiesBundle\Filter\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:40:08.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Filter\VarietyDescriptionFilter;


class VarietyDescriptionFilterTest extends TestCase
{
    /**
     * @var VarietyDescriptionFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionFilter;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Filter\VarietyDescriptionFilter::filter
     * @todo   Implement testFilter().
     */
    public function testFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Filter\VarietyDescriptionFilter::getDefaultOptions
     * @todo   Implement testGetDefaultOptions().
     */
    public function testGetDefaultOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Filter\VarietyDescriptionFilter::getRenderSettings
     * @todo   Implement testGetRenderSettings().
     */
    public function testGetRenderSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
