services:

    librinfo_varieties.admin.family:
        class: Librinfo\VarietiesBundle\Admin\FamilyAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Family, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.family_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:FamilyAdmin:family_edit.html.twig ] ]

    librinfo_varieties.admin.genus:
        class: Librinfo\VarietiesBundle\Admin\GenusAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:GenusAdmin:genus_edit.html.twig ] ]

    librinfo_varieties.admin.genus_embedded:
        class: Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Genus, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.genus_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.species:
        class: Librinfo\VarietiesBundle\Admin\SpeciesAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:SpeciesAdmin:species_edit.html.twig ] ]

    librinfo_varieties.admin.species_embedded:
        class: Librinfo\VarietiesBundle\Admin\SpeciesEmbeddedAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Species, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.species_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety:
        class: Librinfo\VarietiesBundle\Admin\VarietyAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\Variety, LibrinfoVarietiesBundle:VarietyCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ list, LibrinfoVarietiesBundle:VarietyAdmin:list.html.twig ] ]
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:VarietyAdmin:edit.html.twig ] ]

    librinfo_varieties.admin.plant_category:
        class: Librinfo\VarietiesBundle\Admin\PlantCategoryAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\PlantCategory, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.plant_category_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [ edit, LibrinfoVarietiesBundle:PlantCategoryAdmin:plant_category_edit.html.twig ] ]

    librinfo_varieties.admin.variety_description_inner:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_inner_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_professional:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_professional_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_amateur:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_amateur_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_production:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_production_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_commercial:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionCommercial, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_commercial_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_plant:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_plant_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_varieties.admin.variety_description_culture:
        class: Librinfo\VarietiesBundle\Admin\VarietyDescriptionAdmin
        arguments: [~, Librinfo\VarietiesBundle\Entity\VarietyDescriptionCulture, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.varieties.variety_description_culture_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo
