<?php

namespace Librinfo\VarietiesBundle\Entity\Repository;

/**
 * PlantCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
