<?php

namespace Librinfo\VarietiesBundle\Admin\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:44:08.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin;


class GenusEmbeddedAdminTest extends TestCase
{
    /**
     * @var GenusEmbeddedAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new GenusEmbeddedAdmin;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin::getExportFormats
     * @todo   Implement testGetExportFormats().
     */
    public function testGetExportFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin::getExportFields
     * @todo   Implement testGetExportFields().
     */
    public function testGetExportFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin::getDataSourceIterator
     * @todo   Implement testGetDataSourceIterator().
     */
    public function testGetDataSourceIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\GenusEmbeddedAdmin::getBatchActions
     * @todo   Implement testGetBatchActions().
     */
    public function testGetBatchActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
