<?php

namespace Librinfo\VarietiesBundle\Admin\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:42:50.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Admin\GenusAdmin;


class GenusAdminTest extends TestCase
{
    /**
     * @var GenusAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new GenusAdmin;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
