<?php

namespace Librinfo\VarietiesBundle\Admin\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:43:58.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Admin\SpeciesAdmin;


class SpeciesAdminTest extends TestCase
{
    /**
     * @var SpeciesAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new SpeciesAdmin;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\SpeciesAdmin::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Admin\SpeciesAdmin::validateSpeciesCode
     * @todo   Implement testValidateSpeciesCode().
     */
    public function testValidateSpeciesCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
