<?php

namespace Librinfo\VarietiesBundle\Form\ChoiceLoader\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:56:51.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Form\ChoiceLoader\VarietyDescriptionChoiceLoader;


class VarietyDescriptionChoiceLoaderTest extends TestCase
{
    /**
     * @var VarietyDescriptionChoiceLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyDescriptionChoiceLoader;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\ChoiceLoader\VarietyDescriptionChoiceLoader::loadValuesForChoices
     * @todo   Implement testLoadValuesForChoices().
     */
    public function testLoadValuesForChoices()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\ChoiceLoader\VarietyDescriptionChoiceLoader::loadChoiceList
     * @todo   Implement testLoadChoiceList().
     */
    public function testLoadChoiceList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Form\ChoiceLoader\VarietyDescriptionChoiceLoader::loadChoicesForValues
     * @todo   Implement testLoadChoicesForValues().
     */
    public function testLoadChoicesForValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
