<?php

namespace Librinfo\VarietiesBundle\Controller\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:45:27.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\Controller\VarietyCRUDController;


class VarietyCRUDControllerTest extends TestCase
{
    /**
     * @var VarietyCRUDController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new VarietyCRUDController;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\VarietiesBundle\Controller\VarietyCRUDController::hierarchyAction
     * @todo   Implement testHierarchyAction().
     */
    public function testHierarchyAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Controller\VarietyCRUDController::strainAction
     * @todo   Implement testStrainAction().
     */
    public function testStrainAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Controller\VarietyCRUDController::getFilterWidgetAction
     * @todo   Implement testGetFilterWidgetAction().
     */
    public function testGetFilterWidgetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\VarietiesBundle\Controller\VarietyCRUDController::generateEntityCodeAction
     * @todo   Implement testGenerateEntityCodeAction().
     */
    public function testGenerateEntityCodeAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
