<?php

namespace Librinfo\VarietiesBundle\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-30 at 16:45:12.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\VarietiesBundle\LibrinfoVarietiesBundle;


class LibrinfoVarietiesBundleTest extends TestCase
{
    /**
     * @var LibrinfoVarietiesBundle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new LibrinfoVarietiesBundle;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
