Librinfo\VarietiesBundle\Entity\GenericDescription:
    type: mappedSuperclass

    fields:
        field:
            type:     string(255)
            nullable: false
        value:
            type:     text
            nullable: true