Librinfo\VarietiesBundle\Entity\Genus:
    type: entity
    table: genus
    blast:
        loggable: true
    fields:
        latin_name:
            type:     string(255)
            nullable: true
        alias:
            type:     string(255)
            nullable: true

    manyToOne:
        family:
            targetEntity: Librinfo\VarietiesBundle\Entity\Family
            inversedBy: genuses
            joinColumn:
                name: family_id
            cascade: [ persist ]

    oneToMany:
        specieses:
            targetEntity: Librinfo\VarietiesBundle\Entity\Species
            mappedBy: genus
            cascade: [ persist ]

    uniqueConstraints:
        genus_name_idx:
            columns: [ name ]