
Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: production_descriptions
            joinColumn:
                name: variety_id