# info: VarietyDescription extends GenericDescription (mapped superclass)

Librinfo\VarietiesBundle\Entity\VarietyDescription:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: fieldset
        type: string
    discriminatorMap:
        variety: Librinfo\VarietiesBundle\Entity\VarietyDescription
        professional: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProfessional
        amateur: Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur
        production: Librinfo\VarietiesBundle\Entity\VarietyDescriptionProduction
        commercial: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCommercial
        plant: Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant
        culture: Librinfo\VarietiesBundle\Entity\VarietyDescriptionCulture
        inner: Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner
    table: variety_description
    repositoryClass: Librinfo\VarietiesBundle\Entity\Repository\VarietyDescriptionRepository