
Librinfo\VarietiesBundle\Entity\VarietyDescriptionInner:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: inner_descriptions
            joinColumn:
                name: variety_id