
Librinfo\VarietiesBundle\Entity\VarietyDescriptionPlant:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: plant_descriptions
            joinColumn:
                name: variety_id
