
Librinfo\VarietiesBundle\Entity\VarietyDescriptionAmateur:
    type: entity
    manyToOne:
        variety:
            targetEntity: Librinfo\VarietiesBundle\Entity\Variety
            inversedBy: amateur_descriptions
            joinColumn:
                name: variety_id
